services:
  nginx:
    image: alfg/nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
    restart: unless-stopped
    depends_on:
      - web
    networks:
      - my_network
  
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - ./tmp:/app/tmp
      - ./db:/app/db
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:password@postgres:5432/myapp_development
    depends_on:
      - redis
      - postgres
    networks:
      - my_network
    develop:
      watch:
        - path: .
          target: /app
          ignore:
            - node_modules/
          action: sync
        - path: Gemfile
          target: /app/Gemfile
          action: sync
        - path: Gemfile.lock
          target: /app/Gemfile.lock
          action: sync

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - ./tmp:/app/tmp
      - ./db:/app/db
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:password@postgres:5432/myapp_development
    depends_on:
      - redis
      - postgres
    networks:
      - my_network
    develop:
      watch:
        - path: .
          target: /app
          ignore:
            - node_modules/
          action: sync
        - path: Gemfile
          target: /app/Gemfile
          action: sync
        - path: Gemfile.lock
          target: /app/Gemfile.lock
          action: sync

  redis:
    image: redis:6-alpine
    networks:
      - my_network
      
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: