default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("DATABASE_HOST", "postgres") %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  
test:
  <<: *default
  database: myapp_test
  username: postgres
  password: password

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>